# environment.yml
name: protest_safety
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - numpy
  - pandas
  - scipy
  - matplotlib
  - flake8
  - pip
  - pip:
    - gymnasium
    - networkx
    - pyyaml